### ISSUE TITLE
Frage zum aktuell halten der Schulferien

### ISSUE THREAD

**Issue by ypid** [wintermeyer/mehr-schulferien.de#5]
Hallo,

sehr cooles Projekt! Ich bin gerade darauf gestoßen, da ich auf der Suche nach Schulferien Definitionen für ein Programm bin, welches Öffnungszeiten [1] für OpenStreetMap auswertet [2] [3] [4].

[1]: https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours
[2]: https://openingh.ypid.de/evaluation_tool/?EXP=SH%3B%20PH%20off&DATE=1471961280000&lat=48.7769&lon=9.1844&mode=0
[3]: https://openingh.ypid.de/
[4]: https://github.com/opening-hours/opening_hours.js

Ref: https://github.com/opening-hours/opening_hours.js/issues/192

http://www.schulferien.org/ war zwar bislang ganz nett und hat auch in der Vergangenheit alle verfügbaren Ferien als iCal Dateien angeboten, allerdings verfolgt die Seite leider nicht eine FOSS Ansatz. Daher bin ich sehr froh, mit mehr-schulferien.de eine mögliche alternative gefunden zu haben. Meine Frage wäre nur, wie die Schulferien aktuell gehalten werden? Die Schulferien sind in https://github.com/wintermeyer/mehr-schulferien.de/blob/master/db/seeds.rb definiert. Diese werden dort manuell gepflegt? Ich habe bereits ausführlich gesucht, die Schulferien scheinen leider nicht in maschinenlesbarer Form veröffentlicht zu werden, daher ist das wohl der konsequenteste Ansatz. Ich habe mal http://www.schulferien.org/ angefragt, woher die Schulferien bezogen werden, leider ohne Antwort.

Meine Idee wäre gewesen, die HTML Tabelle auf http://www.schulferien.org/ zu parsen, nachdem ich angefragt hatte und es nicht mehr alle keine iCals zum download gibt.

**Comment by wintermeyer** [comment]
Die Daten werden (leider) manuell aktuell gehalten. Das ist sehr kleinteilig und ziemlich aufwendig. Ich bin gerade mit https://www.vutuv.de beschäftigt, sonst hätte ich Dir eine Export API gebaut. Wenn Du es aber selbst programmieren kannst: Einfach einen Pull-Request einstellen.

Danke fürs Feedback!

**Comment by ypid** [comment]
Danke für die Rückmeldung. Ich habe leider keine Ruby Erfahrung :wink: Ich denke eine schöne Export API werde ich vorerst nicht bauen können. Wenn ich die Datenquelle verwende müsste ich das Format sowieso in das Format von opening_hours.js konvertieren. Da wäre ich vermutlich mit export aus Ruby in JSON, dann konvertieren mit Python schneller dran.

> Meine Idee wäre gewesen, die HTML Tabelle auf http://www.schulferien.org/ zu parsen, nachdem ich angefragt hatte und es nicht mehr alle keine iCals zum download gibt.

Was hältst du von der Idee?

**Comment by wintermeyer** [comment]
Ja, Parsen wäre auch mein Weg.

**Comment by ypid** [comment]
> Ja, Parsen wäre auch mein Weg.

Hattest Du eventuell über einen automatischen Import schon mal nachgedacht? Vermutlich ist daraus nichts geworden, weil es keine offiziellen brauchbaren Quellen gibt?

**Comment by wintermeyer** [comment]
Wie Du schon erkannt hast: Es gibt keine offiziellen Quellen.

**Comment by ypid** [comment]
> Ja, Parsen wäre auch mein Weg.

Zur Info: Ich habe es jetzt so implementiert, siehe [hc](https://gitlab.com/ypid/hc).
